// [no, 제목KR, 제목EN, 시계, 사연요약,
//  훅카드[kr,en], 사연VO[[tc,kr,en]...], 대사[[tc,who,kr,en,note]...], 엔딩카드[kr,en], 비고]
const SC = [
["01","줄","THE LINE","11:11",
 "시험에 붙게 해달라 빈 학생. 붙었다. 같이 준비한 친구가 떨어졌다.",
 ["매일 밤 11시 11분, 그 골목에 줄이 선다","EVERY NIGHT AT 11:11, A LINE FORMS IN THAT ALLEY"],
 [["02.4–06","붙게 해달라고 빌었어요. 11시 11분에.","I made a wish at 11:11. Just let me pass."],
  ["06–10","붙었습니다.","I passed."],
  ["10–14","같이 공부한 애는… 떨어졌고요.","The friend I studied with didn't."],
  ["14–18","그게 우연일까요?","Was that a coincidence?"]],
 [["36–40","린","…아무도 없잖아.","There's no one here.","골목 끝. 손목시계 11:10. 혼잣말, 거의 숨소리"],
  ["46–50","린","누구세요?","Who's there?","11:11:00. 뒤돌아본 직후. 대답은 없다"]],
 ["그의 뒤로, 줄이 서 있었다","BEHIND HIM, THE LINE WAS WAITING"],
 "도하 무언. 시즌 내내 그가 대답하지 않는다는 규칙을 1화에서 각인시킨다."],

["02","어머니","MOTHER","9:11",
 "어머니가 낫게 해달라 빈 아들. 나았다. 그런데 아들을 알아보지 못한다.",
 ["소원은 이뤄진다. 정확히 빈 대로만","WISHES COME TRUE. EXACTLY AS ASKED."],
 [["02.4–06","엄마가 낫게만 해달라고 빌었어요.","I only wished my mother would get well."],
  ["06–10","다음 날 퇴원했습니다.","She was discharged the next day."],
  ["10–14","그런데 저를 못 알아봅니다.","But she doesn't know who I am."],
  ["14–18","…'낫게'만 빌었으니까요.","I only asked for 'well.'"]],
 [["40–44","린","…줄어들고 있어.","It's going down.","시계 클로즈업 컷 직후. 깨달음. 심장박동 비트"],
  ["48–52","린","잠깐만요!","Wait—","11:11:50. 뛰어들어 손목을 잡는다"]],
 ["11:12. 남은 건 부품 하나","11:12. ONE GEAR LEFT ON THE GROUND"],
 "그가 만진 물건은 남는다 — 규칙을 대사 없이 물건 하나로 심는다. 5화 열쇠가 된다."],

["03","돌아와","COME BACK","7:11",
 "헤어진 연인이 돌아오게 해달라. 돌아왔다. 그런데 왜 왔는지 본인도 모른다.",
 ["그를 찾는 건 나만이 아니었다","I WASN'T THE ONLY ONE LOOKING FOR HIM"],
 [["02.4–06","돌아오게만 해달라고 빌었어요.","I only wished he'd come back."],
  ["06–10","돌아왔습니다.","He came back."],
  ["10–14","근데 왜 왔는지 자기도 모른대요.","He doesn't know why he came."],
  ["14–18","사랑은… 빌지 않았거든요.","I never wished to be loved."]],
 [["20–24","린","여긴 아무도 몰라요.","No one knows this place.","폐건물 옥상. 그를 옮긴 직후"],
  ["56–60","린","…내가 흘렸구나.","It was me.","자기 방송 녹취 위에 겹친다"]],
 ["내가 위치를 흘렸다","I GAVE HIM AWAY"],
 "48–55초 아카이브 음성(대사 아님) — 린의 방송: \"그 골목은, 세 번째 가로등에서…\""],

["04","거울","MIRROR","6:11",
 "젊어지게 해달라 빈 남자. 젊어졌다. 이제 아무도 그를 알아보지 못한다.",
 ["거울 속 얼굴이 낯설다","THE FACE IN THE MIRROR IS A STRANGER"],
 [["02.4–06","다시 젊어지게 해달라고 빌었습니다.","I wished to be young again."],
  ["06–10","이뤄졌어요.","It came true."],
  ["10–14","이제 아무도 저를 모릅니다.","Now no one knows me."],
  ["14–18","가족도요.","Not even my family."]],
 [["22–26","PD","청취율 1위야. 왜 접어?","We're number one. Why kill it?","코너 폐지 신청서를 밀어 돌려준다"],
  ["48–52","린","나 어떻게 되는 거예요?","What's happening to me?","도하는 대답하지 않는다. 3초 정적"]],
 ["나는 어제를 기억하지 못한다","I CAN'T REMEMBER YESTERDAY"],
 "38–44초 노트 인서트(화면 텍스트, 손글씨): \"11:11 — 그를 만났다\" · 자기 글씨인데 기억이 없다"],

["05","이름","THE NAME","4:11",
 "잊게 해달라 빈 사람. 잊었다. 소중한 것까지 전부.",
 ["멈춘 시계 수백 개. 전부 11:11","HUNDREDS OF STOPPED CLOCKS. ALL AT 11:11"],
 [["02.4–07","다 잊게 해달라고 빌었어요.","I wished to forget everything."],
  ["07–11","잊었습니다.","I did."],
  ["11–16","이제… 제가 뭘 잃었는지도 모릅니다.","Now I don't even know what I lost."]],
 [["56–60","린","……서린.","…Seo-rin.","이름표를 읽는다. 자기 이름. 이 화 유일한 대사"]],
 ["이름표에는, 내 이름","THE TAG READS: SEO-RIN"],
 "16–54초 전 구간 무대사. 시계방 시퀀스는 소리(초침·자물쇠·문)로만 끌고 간다."],

["06","부름","THE CALL","3:11",
 "다시 만나게 해달라 빈 사람. 만났다. 장례식장에서.",
 ["그를 부르는 건 나였다","I WAS THE ONE CALLING HIM"],
 [["02.4–07","다시 만나게만 해달라고 빌었어요.","I only wished to see them again."],
  ["07–11","만났습니다.","I did."],
  ["11–16","장례식장에서요.","At the funeral."]],
 [["18–22","린","오늘은 생각하지 않는다.","Today I won't think of him.","눈을 감고 자기에게 하는 말"],
  ["56–60","린","…내가 죽이고 있었어.","I've been killing him.","몽타주 끝, 정면"]],
 ["그를 부를까 · 놓아줄까","CALL HIM · LET HIM GO"],
 "44–54초 몽타주 자막(화면 텍스트): 「생각한 날 −1분」 / 「생각하지 않은 날 −0」 · 엔딩 카드는 댓글 투표"],

["07","문장","THE SENTENCE","2:11",
 "유명해지게 해달라 빈 사람. 됐다. 사고 영상으로.",
 ["참으면, 더 세게 온다","THE HARDER I RESIST, THE HARDER HE COMES"],
 [["02.4–07","유명해지게 해달라고 빌었어요.","I wished to be known."],
  ["07–11","됐습니다.","I am."],
  ["11–14","사고 영상으로요.","From the crash footage."]],
 [["54–57","린","왜 자꾸 오는 거예요?","Why do you keep coming?","창밖 인파를 등지고 돌아선다"],
  ["57–60","도하","묻지 마세요. 물을수록 짧아집니다.","Don't ask. Every question makes it shorter.","★ 도하의 첫 문장. 마지막 컷 5초 고정"]],
 ["—","—"],
 "엔딩 카드 없음. 도하의 문장이 엔딩이다. 14–30초는 전 구간 무대사·무음악, 생활음만."],

["08","11월 11일","NOVEMBER 11","1:11",
 "오늘 하루만 행복하게 해달라. 이뤄졌다. 딱 하루만.",
 ["오늘, 전 세계가 같은 시각에 빈다","TONIGHT THE WHOLE WORLD WISHES AT ONCE"],
 [["02.4–07","오늘 하루만 행복하게 해달라고 빌었어요.","I wished for one happy day."],
  ["07–11","그날 하루는… 정말 행복했습니다.","And that day, I was."],
  ["11–14","딱 하루였어요.","One day. That was all."]],
 [["34–38","린","다들… 같은 시각에 빌잖아.","They all wish at the same time.","피드를 넘긴다. 전 세계 11:11 게시물"],
  ["56–60","린","멈춰. 제발.","Stop. Please.","시계 숫자가 초 단위로 떨어진다"]],
 ["숫자가 멈추지 않는다","THE NUMBER WON'T STOP"],
 "14–30초 글로벌 훅: 도쿄·상하이·뉴욕·파리 간판과 전광판이 전부 11:11. 각국 언어 화면 텍스트 \"11:11 make a wish\"."],

["09","대신","INSTEAD","0:33",
 "누군가를 위해 대신 아프게 해달라 빈 사람. 그건 그대로 이뤄졌다.",
 ["이번 소원만은, 어긋나지 않았다","THIS ONE WISH CAME TRUE UNBROKEN"],
 [["02.4–07","제가 대신 아프게 해달라고 빌었어요.","I wished to hurt in their place."],
  ["07–12","그대로 됐습니다.","And it happened, exactly."],
  ["12–16","…이건, 어긋난 게 아니죠?","That one wasn't twisted. Was it?"]],
 [["34–38","린","내가 대신할게요.","Let me take it.","이름표 붙은 자기 시계를 내민다"],
  ["46–50","린","누구 값인지 안 물을게요.","I won't ask whose debt it is.","도하의 표정이 처음 흔들린다. 그리고 고개를 젓는다"]],
 ["받을까 · 거절할까","TAKE IT · REFUSE"],
 "린의 두 번째 대사가 규칙 9(누구를 위한 값인지 모른 채 동의해야 이전된다)를 설명 없이 심는다. 10화 결말의 개연성은 여기서 완성된다."],

["10","11초","ELEVEN SECONDS","0:11",
 "이 화의 사연은 린의 것이다. 코너에 마지막으로 도착한 사연은 그녀가 쓴 것이었다.",
 ["11초 남았다","ELEVEN SECONDS LEFT"],
 [["02.4–06","마지막 사연입니다.","One last letter."],
  ["06–10","매일 밤 11시 11분에, 한 사람을 기다렸습니다.","Every night at 11:11, I waited for someone."],
  ["10–14","그를 기다린 게… 그를 없앴습니다.","The waiting is what erased him."],
  ["14–16","그래도 한 번만 더 보고 싶었어요.","I still wanted to see him one more time."]],
 [["38–48","도하","당신이 처음이었습니다.","You were the first.","★ 도하의 두 번째이자 마지막 문장. 이 화 유일한 대사"]],
 ["아침. 아무 기억도 없다","MORNING. SHE REMEMBERS NOTHING"],
 "16–38초 붉은 카운트다운 자막 11·10·9…1·0 위로 1–9화 컷이 스친다. 사연 목소리가 린의 것이었다는 건 14초 지점에서 음성이 현장음과 겹치며 드러난다."],
];
module.exports = {SC};
